name: connexion-example
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python=3.6.3=1
- yaml=0.1.7=0
- connexion=1.1.10=py36_0
- pymongo=3.4.0=py36_0
- gunicorn=19.8.1=py36_0
- flask-cors=3.0.6=py36_0
- pandas=0.23.4
- scikit-learn=0.20.0
- gevent=1.1.2
